# Generated by Django 2.2.6 on 2019-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191018_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name_plural': 'Routes'},
        ),
    ]
